### ISSUE TITLE
Atualizar Roadmap para 2023/2024

### ISSUE THREAD

**Issue by CristovoXDGM** [Flutterando/roadmap#5]
@jacobaraujo7 @tauamendonca @AlvaroVasconcelos @Flutterando/fteam  seria interessante ser feita uma atualização nesse roadmap com novos conhecimentos que foram obtidos ao longo do ano e atualizar alguns que ja estão presentes

**Comment by thKali** [comment]
tem alguma sugestão de novos conteúdos? foi atualizado recentemente mas mexemos em poucas coisas

**Comment by CristovoXDGM** [comment]
Tem algumas coisas internas que era interessante atualizar, conhecimentos e dicas que foram obtidas através de projetos, por isso marquei o jacob e o restante do time @thKali

**Comment by CristovoXDGM** [comment]
Estarei fechando a issue, tendo em vista que os PRs que estavam pendentes de atualização foram mergeados.
