### ISSUE TITLE
Criar uma Versão em inglês do roadmap

### ISSUE THREAD

**Issue by CristovoXDGM** [Flutterando/roadmap#7]
O roadmap atual atende bem a necessidade de todo mundo, porém tenho notado que tem pessoas de fora que querem usar o roadmap, seria interessante fazer essa tradução do roadmap, primariamente pro ingles e quem sabe outras línguas no futuro.

**Comment by CristovoXDGM** [comment]
@jacobaraujo7 @davidsdearaujo @Bwolfs2

**Comment by CristovoXDGM** [comment]
@toshiossada

**Comment by toshiossada** [comment]
o ruim é q os conteúdos q indicamos é em português, poderia até traduzir, mas não conheço muito conteúdo em inglês

**Comment by CristovoXDGM** [comment]
Por isso a ideia dessa issue, é literalmente se não conseguir traduzir, procurar conteúdos que possam preencher essa lacuna temporariamente, até conseguir produzir o restante @toshiossada

**Comment by davidsdearaujo** [comment]
Acho que não deveríamos considerar como uma tradução, mas sim um roadmap específico para cada língua. Podemos até utilizar informações em comum, mas cada roadmap poderia crescer separadamente

**Comment by lucassfernando** [comment]
Pessoal, eu achei a ideia legal. Como podemos começar organizando isso? Organizando cada linguagem em uma pasta?

**Exemplo:**
ROADMAP PT-BR --> caminhos para aprender em português
REOADMAP EN --> caminhos para aprender em inglês

Seria mais ou menos assim?
